/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as SareesRouteImport } from './routes/sarees'
import { Route as IndexRouteImport } from './routes/index'

const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const SareesRoute = SareesRouteImport.update({
  id: '/sarees',
  path: '/sarees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sarees': typeof SareesRoute
  '/try-on': typeof TryOnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sarees': typeof SareesRoute
  '/try-on': typeof TryOnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sarees': typeof SareesRoute
  '/try-on': typeof TryOnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sarees' | '/try-on'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sarees' | '/try-on'
  id: '__root__' | '/' | '/sarees' | '/try-on'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SareesRoute: typeof SareesRoute
  TryOnRoute: typeof TryOnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sarees': {
      id: '/sarees'
      path: '/sarees'
      fullPath: '/sarees'
      preLoaderRoute: typeof SareesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SareesRoute: SareesRoute,
  TryOnRoute: TryOnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
